### ISSUE TITLE
Name or service not known in kubernetes deployment

### ISSUE THREAD

**Issue by JovanShandro** [decentralized-identity/universal-resolver#188]
Hello!

I am trying to create a kubernetes deployment for the uni-resolver-web. This is my yaml file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-resolver-web
  namespace: default
  labels:
    app: uni-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-resolver-web
  template:
    metadata:
      labels:
        app: uni-resolver-web
    spec:
      containers:
      - name: uni-resolver-web
        image: universalresolver/uni-resolver-web
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uni-resolver-web
spec:
  type: NodePort
  selector:
    app: uni-resolver-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
```

However when I try to access {ingressHost}/1.0/identifiers/did:web:did.actor:alice

I get the following response
```
Resolve problem for did:web:did.actor:alice: 
Cannot retrieve RESOLVE RESULT for did:web:did.actor:alice from 
http://uni-resolver-driver-did-uport:8081/1.0/identifiers/did:web:did.actor:alice: 
uni-resolver-driver-did-uport: Name or service not known
```
