### ISSUE TITLE
Indy and Sov DIDs are not resolving -> Empty Pool Config

### ISSUE THREAD

**Issue by dennisn00** [decentralized-identity/universal-resolver#390]
I set up the Resolver locally in a Docker container and ran
 `curl -X GET http://localhost:8080/1.0/identifiers/did:indy:idunion:BDrEcHc8Tb4Lb2VyQZWEDE`
 which is the example for Indy given in the Readme.
This took over a minute and returned 
`Resolve problem for did:indy:idunion:BDrEcHc8Tb4Lb2VyQZWEDE: A value must be provided for the 'pool' parameter`

The same happened for the Sov DID example. I tried a few other DID Methods and they worked fine.
I checked the logs of the driver-did-indy container and it seemed like the environment variable poolConfig was indeed not set.
I saw that in the [docker-compose.yml](https://github.com/decentralized-identity/universal-resolver/blob/main/docker-compose.yml), the poolConfig Environment variable seems to be overwritten with an empty/undefined value.
I removed all those lines as shown below, and restarted the containers.
``` 
driver-did-indy:
    image: universalresolver/driver-did-indy:latest  
    #environment:
    #  uniresolver_driver_did_indy_libIndyPath: ${uniresolver_driver_did_indy_libIndyPath}  
    #  uniresolver_driver_did_indy_poolConfigs: ${uniresolver_driver_did_indy_poolConfigs}  
    #  uniresolver_driver_did_indy_poolVersions: ${uniresolver_driver_did_indy_poolVersions}  
    #  uniresolver_driver_did_indy_walletNames: ${uniresolver_driver_did_indy_walletNames}  
    #  uniresolver_driver_did_indy_submitterDidSeeds: ${uniresolver_driver_did_indy_submitterDidSeeds}  
    ports:  
      - "8128:8080"  
```
 This time, the poolConfig was indeed set to the value given in the [Driver's Dockerfile](https://github.com/decentralized-identity/uni-resolver-driver-did-indy/blob/main/docker/Dockerfile). I ran the same curl request and got a 
`Driver: No resolve result for did:indy:idunion:BDrEcHc8Tb4Lb2VyQZWEDE`.
I tried the same DID on https://dev.uniresolver.io/ and received the same result, so I believe this DID might not exist anymore.
I then took the first DID I could find in the Indy Tx Explorer, `did:indy:idunion:BNrX6yZzHkKbBGv5aX6PR4`, and it
successfully resolved on both, my local instance and `https://dev.uniresolver.io/`.

I would suggest to remove the lines from docker-compose.yml as shown above unless there is any reason to keep them and update the Readme with a working did:indy: example.
