### ISSUE TITLE
Universal resolver does not pass URL parameters to the backend driver

### ISSUE THREAD

**Issue by ilya-korotya** [decentralized-identity/universal-resolver#437]
I have two containers:

1. **Universal resolver web container**
2. **iden3 DID driver container**

I used the following pattern to register the driver:

```yaml
- pattern: "^(did:iden3:.+)$"
  url: ${uniresolver_web_driver_url_did_iden3:http://driver-did-iden3:8080/}
  propertiesEndpoint: "true"
  testIdentifiers:
    - did:iden3:polygon:amoy:xC8VZLUUfo5p9DWUawReh7QSstmYN6zR7qsQhQCsw
```

**Local Setup:**

```yaml
version: "3.6"

networks:
  default:
    name: universal-resolver

services:
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
    environment:
      uniresolver_web_driver_url_did_polygonid: http://host.docker.internal:8081
      uniresolver_web_driver_url_did_iden3: http://host.docker.internal:8081
      LOG_LEVEL: "debug"
```

When I make a request to the universal resolver web container using `curl` and URL parameter `signature=EthereumEip712Signature2021`, like this:

```bash
curl "http://localhost:8080/1.0/identifiers/did%3Apolygonid%3Apolygon%3Aamoy%3A2qY71pSkdCsRetTHbUA4YqG7Hx63Ej2PeiJMzAdJ2V?signature=EthereumEip712Signature2021"
```

The URL parameter doesn't seem to be passed to the iden3 driver container.
